### ISSUE TITLE
No frontiers at first step

### ISSUE THREAD

**Issue by ebhrz** [cvg/FrontierNet#5]
Thanks for your amazing work, but I got a problem when running the explore demo. It struggles at the first step, the terminal outputs:

```
python demo_exploration.py  --mesh /home/hrz/project1/hm3d/00876-mv2HUxq3B53/mv2HUxq3B53.glb --config config/hm3d_exploration.yaml  --write_path output/exploration_state.json 
/media/hrz/data3/miniconda3/envs/frontiernet/lib/python3.11/site-packages/unik3d/ops/losses/robust_loss.py:195: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream
Open3D version: 0.19.0
load mesh: TriangleMesh with 452854 points and 416502 triangles, and textures of size (2048, 2048) ...
WaveMapper initialized with parameters:
min_cell_width: 0.05
width: 480
height: 480
fx: 300.0
fy: 300.0
cx: 239.5
cy: 239.5
min_range: 0.05
max_range: 3.5
resolution: 0.1
[13:44:30] INFO:root: Loading model from: model_weights/rgbd_11cls.pth
[13:44:30] INFO:root: Using device cuda
[13:44:30] INFO:root: Model loaded! Num classes: 11
Logger initialized with level: INFO
Logger initialized with level: INFO
 frontier.base - INFO - FrontierManager initialized
Logger initialized with level: INFO
 root - INFO -  --- You are in manual mode, you can move the camera using WASD(translation), JL(rotation), QZ(height) keys in the small window ---
 root - INFO -  --- PRESS SPACE TO START EXPLORATION --- 
  root - INFO - Initial mapping round started.
 root - INFO -  -------Current exploration step: 0 -------
 root - INFO - Updating frontiers.
 root - INFO - No frontiers, exploration finished.
 root - INFO - Exploration finished, total steps: 0

```
How can I fix it?

**Comment by ebhrz** [comment]
I identified the root cause of the issue: it stems from an older version of HDBSCAN. Specifically, on Ubuntu 20.04, the default installed version (e.g., 0.8.40 via pip) lacks support for the force_all_finite keyword in check_array(), which was introduced in HDBSCAN ≥ 0.8.41. Since upgrading to 0.8.41 requires manual compilation on that platform, the call at https://github.com/cvg/FrontierNet/blob/66bbc8962820677c46b118d92296abd53ded17df/frontier/detector.py#L283 raises:

```python
TypeError: check_array() got an unexpected keyword argument 'force_all_finite'
```
However, this exception is silently caught and ignored at https://github.com/cvg/FrontierNet/blob/66bbc8962820677c46b118d92296abd53ded17df/frontier/detector.py#L286, resulting only in a misleading "no frontiers detected" log.

I’ll submit a PR to update the dependency specification in requirements.txt to enforce hdbscan>=0.8.41.

**Comment by BoySun045** [comment]
Hi @ebhrz , apologies for the late response, and thanks for spotting this!
Please feel free to open a PR. We would be very happy and grateful to merge the fix.
If you have other plans or ideas, just let us know. We truly appreciate the help and feedback.

Thanks again!

**Comment by ebhrz** [comment]
Hi @BoySun045 , I've submitted a PR. Just change the requirements.txt :)
